### ISSUE TITLE
I use the models in gnn/result/bert-504-gin0jk-5-128/*.pth and run measure.py. Why is the result of F1 0.08?

### ISSUE THREAD

**Issue by e888llll** [Bowen-n/MCBG#1]
![image](https://github.com/Bowen-n/MCBG/assets/32814917/16a13d9f-6704-4cfe-8a29-1f92d7bda7dd)

**Comment by ashrafflh** [comment]
Hi @e888llll,

can you please tell me what Dataset class did you use to work with the models in gnn/result/bert-504-gin0jk-5-128?
All the dataset classes need extra files that are not present in the repo, except from CFGDataset_MAGIC, but this one needs models with 20 features, which are also not present.

Thank you!
